name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn build
      - id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version-packages
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.changesets.outputs.hasChangesets == 'false'
        run: npm publish --workspaces --access public --loglevel=verbose
        env:
          NPM_CONFIG_PROVENANCE: 'true'
